# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.jb_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.IntegerField(choices=[(0, 'Компания'), (1, 'Частное лицо')], default=1, verbose_name='Тип владельца')),
                ('name', models.CharField(help_text='наименование компании или ФИО владельца', max_length=50, verbose_name='Наименоване владельца')),
                ('phone', models.CharField(help_text='номер мобильного телефона', max_length=50, validators=[utils.jb_validators.validate_mobile_phone], verbose_name='Номер мобильного телефона')),
                ('trustee', models.BooleanField(default=False, verbose_name='Доверенное лицо')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='owners/%Y/%m/%d/', verbose_name='Фотография владельца')),
                ('address', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Адрес')),
                ('coord_x', models.FloatField(blank=True, help_text='карта отображается при наличии адреса', null=True, verbose_name='Координата X на карте')),
                ('coord_y', models.FloatField(blank=True, help_text='карта отображается при наличии адреса', null=True, verbose_name='Координата Y на карте')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='citys.City', verbose_name='Город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Объект пользователя')),
            ],
            options={
                'verbose_name': 'владелец',
                'verbose_name_plural': 'владельцы',
            },
        ),
    ]
